#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Project_1.Resource", IsApplication=true)]

namespace Project_1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int day_name = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cell_shape = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int map = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ViewCellBackground = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int btnAddClass = 2131099650;
			
			// aapt resource value: 0x7f060013
			public const int btnCancel = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int btnClass = 2131099673;
			
			// aapt resource value: 0x7f060012
			public const int btnConfirm = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int btnDelete = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int btnDetails = 2131099674;
			
			// aapt resource value: 0x7f060016
			public const int btnEdit = 2131099670;
			
			// aapt resource value: 0x7f060003
			public const int btnEditClass = 2131099651;
			
			// aapt resource value: 0x7f060022
			public const int btnSave = 2131099682;
			
			// aapt resource value: 0x7f06000e
			public const int lblDay = 2131099662;
			
			// aapt resource value: 0x7f06001e
			public const int lblEmail = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int lblName = 2131099677;
			
			// aapt resource value: 0x7f060009
			public const int lblRoom = 2131099657;
			
			// aapt resource value: 0x7f060020
			public const int lblStudy = 2131099680;
			
			// aapt resource value: 0x7f06000b
			public const int lblTime = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int lblTitle = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int lblType = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int lblUnitCode = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int linearLayoutBtns = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int lvClassList = 2131099653;
			
			// aapt resource value: 0x7f06001c
			public const int lvTodayClass = 2131099676;
			
			// aapt resource value: 0x7f06000f
			public const int spinnerDay = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int textView1 = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int titleAddClass = 2131099654;
			
			// aapt resource value: 0x7f060018
			public const int txtDay = 2131099672;
			
			// aapt resource value: 0x7f06001f
			public const int txtEmail = 2131099679;
			
			// aapt resource value: 0x7f060017
			public const int txtName = 2131099671;
			
			// aapt resource value: 0x7f06000a
			public const int txtRoom = 2131099658;
			
			// aapt resource value: 0x7f060021
			public const int txtStudyCourse = 2131099681;
			
			// aapt resource value: 0x7f06000c
			public const int txtTime = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int txtTimes = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int txtType = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int txtUnitCode = 2131099656;
			
			// aapt resource value: 0x7f06001b
			public const int txtWeek = 2131099675;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClassList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int custom_dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int custom_dialog_edit_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int custom_edittext = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int custom_spinner_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int listview_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int UserDetails = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
